Algoritmo "Conversor de graus"

Var

seno, cosseno, tangente, grau: real

Inicio

escreval("Digite o valor do angulo em graus: ")
leia(grau)

seno <- Int(Sen(GraupRad(grau)))

cosseno <- Int(Cos(GraupRad(grau)))

tangente <- Int(Tan(GraupRad(grau)))

escreval("Seno de ",grau," radiano e igual a: ", seno)
escreval("Cosseno de ",grau," radiano e igual a: ", cosseno)
escreval("Tangente de ",grau," radiano e igual a: ", tangente)

Fimalgoritmo