Algoritmo "Comparar numeros"

Var
a, b, c: inteiro


Inicio
escreval("Digite primeiro numero: ")
leia(a)
escreval("Digite segundo numero: ")
leia(b)
escreval("Digite terceiro numero: ")
leia(c)

se (a = b) entao
escreval("Letra a é igual b ")
fimse
se (a > b) entao
escreval("Letra a maior que b")
fimse
se (c < b) entao
escreval("Letra c menor que b ")
fimse
se (c <> b) entao
escreval("Letra c é diferente de b")
fimse

escreval("Valores  a:",a, " b:",b, " c:",c)



Fimalgoritmo